name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggert auf Tags wie v1.0.0, v1.0.1, etc.
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Dependencies with Constraint
      run: python -m pip install -r requirements.txt

    - name: Run Build Script
      run: python build_script.py  # Führt dein Build-Skript aus

    - name: Zip the .app file
      run: |
        cd dist
        zip -r Mastermind.zip Mastermind

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Build Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/Mastermind  # Pfad zur erstellten .app Datei
        asset_name: Mastermind.zip  # Name der Datei im Release
        asset_content_type: application/zip
