name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggert auf Tags wie v1.0.0, v1.0.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.5'

    - name: Ensure pip is installed and upgraded
      run: |
          python -m ensurepip --upgrade  # Stellt sicher, dass pip in Python 3.12 installiert ist
          python -m pip install --upgrade pip  # Aktualisiert pip auf die neueste Version

    - name: Install Dependencies
      run: |
          python -m pip install --upgrade setuptools  # Setuptools aktualisieren
          python -m pip install numpy==1.26.4  # Kompatible numpy Version für Python 3.12
          python -m pip install -r requirements.txt

    - name: Run Build Script
      run: |
        python build_script.py  # Führt dein Build-Skript aus

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Build Artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/Mastermind.app  # Pfad zur erstellten .app Datei
        asset_name: Mastermind.app  # Name der Datei im Release
        asset_content_type: application/octet-stream
